{{- $strategyBlock := index .Values.global .Values.global.releaseEnvironment  -}}
{{- range $strategyName, $strategy := $strategyBlock -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hummingbot-conf
  namespace: {{ include "resource.namespace" $ }}
  labels:
    app: {{ $strategyName }}
    helm.sh/chart: {{ include "chart.chart" $ }}
data:
  conf_global.yml: |
    #################################
    ###   Global configurations   ###
    #################################

    # For more detailed information: https://docs.hummingbot.io
    template_version: 7

    # Exchange configs
    bamboo_relay_use_coordinator: false
    bamboo_relay_pre_emptive_soft_cancels: false

    ethereum_wallet:
    ethereum_rpc_url:
    ethereum_chain_name: MAIN_NET
    ethereum_token_overrides: {}

    # Kill switch
    kill_switch_enabled: false
    ## The rate of performance at which you would want the bot to stop trading (-20 = 20%)
    kill_switch_rate: -100.0

    # Paper Trading
    paper_trade_enabled: {{ $strategy.options.paperTrade }}
    paper_trade_account_balance:
    - - USDT
      - 10000
    - - ONE
      - 1000
    - - USDQ
      - 1000
    - - TUSD
      - 1000
    - - ETH
      - 10
    - - WETH
      - 10
    - - USDC
      - 1000
    - - DAI
      - 1000
    - - USD
      - 1000
    - - FTH
      - 10
    - - XETH
      - 10
    - - XTZ
      - 1000
    - - ZUSD
      - 10000

    # Telegram integration
    telegram_enabled: false
    telegram_token:
    telegram_chat_id:

    # Exchange rate
    exchange_rate_default_data_feed: coin_gecko_api
    exchange_rate_conversion:
    - - USD
      - 1.0
      - manual
    - - DAI
      - 1.0
      - coin_gecko_api
    - - USDT
      - 1.0
      - coin_gecko_api
    - - USDC
      - 1.0
      - coin_gecko_api
    - - TUSD
      - 1.0
      - coin_gecko_api
    exchange_rate_fetcher:
    - - ETH
      - coin_gecko_api
    - - DAI
      - coin_gecko_api
    send_error_logs: false

    # Advanced configs: Do NOT touch unless you understand what you are changing
    client_id: 67b8dc40283f02da56075d968eebbdbb2b0f84e6
    log_level: INFO
    debug_console: false
    strategy_report_interval: 900.0
    logger_override_whitelist:
    - hummingbot.strategy.arbitrage
    - hummingbot.strategy.cross_exchange_market_making
    - conf
    key_file_path: conf/
    log_file_path: logs/
    on_chain_cancel_on_exit: false

    # Minimum default order amount (in quote currency), this is used for when prompting a new order_amount.
    min_quote_order_amount:
    - - BTC
      - 0.0011
    - - ETH
      - 0.05
    - - USD
      - 11
    - - BNB
      - 0.5

    SLACK_HOOK: https://hooks.slack.com/services/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
---
{{- end -}}
